### PR TITLE
Fixed a small bug with the new hud_itemclocks (style 6 and 7) y spacing

### PR DESCRIPTION
**Pull request by tcsabina**

### CODE REVIEW

**Comment by tcsabina** [comment]
Hi meag,

any chance this lands in 3.6 someday? A super simple 'bug-fix'...

**Comment by meag** [comment]
Did I break it again with the merge with 3.1?

**Comment by tcsabina** [comment]
> 
> 
> Did I break it again with the merge with 3.1?

nooo :)

I made a big during the initial PR... ;)

I guess, noone really uses these new item_timers. Otherwise we would have heard complains that it doesn't look okay on the screen.
But still, we should fix this.

**Comment by tcsabina** [comment]
Hi meag,
I think we can close this PR.
I made a new one for the master ezquake branch, as I guess this 'meag-renderer' is kind of obsolete.

**Pull request closed without merging**
