### PR TITLE
add Client2Server packet duplication feature, a la Qizmo

### PR DESCRIPTION
**Pull request by mushis**
as the title says. i've ported the change done in mvdsv (i've requested a pull on mvdsv also) to ezQuake.

FTE already has it, Spike helped me in the process. more infor in the mvdsv pull request. 
thanks!

### CODE REVIEW

**Comment by deurk** [comment]
@meag Let me know when you merge this, I'll merge associated https://github.com/deurk/mvdsv/pull/44

**Comment by mushis** [comment]
just wanted to say that, in principle, it isn't required to have this implemented on the server to be able to implement it in the client. Recommended, but not required.

**Comment by tcsabina** [comment]
upping this.
Hard work (implementation) is already done, so why not merge the PR?

Even to this date (mid 2021) there are players with PL issues. This feature could help them...

**Comment by tcsabina** [comment]
@meag , any reason not merging this?

**Comment by meag** [comment]
@tcsabina it was, with minor changes https://github.com/meag/ezquake-source/commit/ac63600530e03f708506f474bf4c2130909a84d0

**Pull request closed without merging**
